### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by enbyspiders** [tinypalace/tinypalace.github.io#1]
- [x] Impressum text final machen
- [x] safer spaces
- [x] großes logo/aufmacher
- [x] index seite layout? (alle infos auf einer seite?)
- [x] blog layout
- [x] runde bilder?
- [x] about text
- [x] translate!!
- [x] newsletter?
- [x] forms und open call
- [x] telefonnummer
- [x] change logo size?
- [x] presskit
- [x] make forms work
- [x] blog list

**Comment by voec** [comment]
- [ ] forms und open call
- [ ] telefonnummer
